---
title: "MATH 216 Homework 4 Shiny App"
author: "James Burke"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Suggested packages; feel free to use more!
library(tidyverse)
library(USAboundaries)
library(maptools)
library(sp)
library(broom)

# Extract Population Data
county_pop_data <- read_csv(file="County_Data.csv") %>%
  rename(
    Pop_Total = SE_T001_001,    # Total Population
    Pop_Density = SE_T002_002   # Population Density
    ) %>% 
  select(Geo_NAME, Geo_COUNTY, Geo_FIPS, Pop_Total, Pop_Density)

# Get County Spatial Polygons Data Frame
county_shp <- us_counties()

# Generate Centroid Values
centroids <- data.frame(coordinates(county_shp))

# Bind Centroid Values to County Data
county_data <- bind_cols(county_shp@data, centroids) %>% 
  rename(
    centroid_long = X1,
    centroid_lat = X2
  ) %>% 
  mutate(
    # creating geographic FIPS codes
    Geo_FIPS = as.numeric(paste(statefp, countyfp, sep = ""))
  )

# Joining Population Data with County Data
hub_data <- left_join(county_data, county_pop_data, by = "Geo_FIPS") %>%
  filter(!statefp %in% c("02", "15", "72")) # exclude Alaska, Hawaii, & Puerto Rico

hub_data <- hub_data %>%
  mutate(
    weighted_long = centroid_long * Pop_Total,
    weighted_lat = centroid_lat * Pop_Total
  ) %>% 
  select(Geo_FIPS, Pop_Total, weighted_long, weighted_lat) %>% 
  filter(!is.na(Pop_Total))

# Calculating Hub Location - using center of mass formula
hub_x_coord <- sum(hub_data$weighted_long) / sum(hub_data$Pop_Total)
hub_y_coord <- sum(hub_data$weighted_lat) / sum(hub_data$Pop_Total)
```


## Inputs and Outputs

You can embed Shiny inputs and outputs in your document. Outputs are automatically updated whenever inputs change.  This demonstrates how a standard R plot can be made interactive by wrapping it in the Shiny `renderPlot` function. The `selectInput` and `sliderInput` functions create the input widgets used to drive the plot.

```{r eruptions, echo=FALSE}
inputPanel(
  # Input Borders
  radioButtons("level", label = "Level:", c("State", "County"), 
               select = "State", inline = TRUE),
  radioButtons("hub", label = "Hub Location:", c("Calculated", "Logistical"),
               select = "Calculated", inline = TRUE)
)

renderPlot({
  
  if(input$level == "State") chart_shp <- us_states()
  if(input$level == "County") chart_shp <- us_counties()
  
  if(input$hub == "Logistical") {
    hub_x_coord <- -90.384601
    hub_y_coord <- 38.849079
  }
  
  centroids <- data.frame(coordinates(chart_shp))

  chart_data <- bind_cols(chart_shp@data, centroids) %>% 
    rename(
      centroid_long = X1,
      centroid_lat = X2
    )
  
  chart_polygon <- tidy(chart_shp, region="geoid")
  
  geo_data <- left_join(chart_polygon, chart_data, by=c("id"="geoid")) %>%
    filter(!statefp %in% c("02", "15", "72"))
  
  geo_data <- geo_data %>% 
    mutate(distance = sqrt(
      (centroid_long - hub_x_coord)^2 + 
        (centroid_lat - hub_y_coord)^2
    ))
  
  ggplot(data=geo_data, aes(x=long, y=lat, group=group, fill=distance)) +
    # Plot choropleth polygons, low -> high being colored white -> dark green
    geom_polygon() +
    scale_fill_gradient(low="white", high="darkgreen") + 
    # Trace outlines of areas
    geom_path(size=0.1) +
    # Mark hub
    annotate("point", x=hub_x_coord, y=hub_y_coord, col="red", size=5) +
    # Correct aspect ratio for map
    coord_map()
})
```
